### ISSUE TITLE
Pretrained model weights tar file corrupt

### ISSUE THREAD

**Issue by florianblume** [kreimanlab/Put-In-Context#1]
Hi,

first of all thanks for putting your code online! I needed to adapt your code a bit to make it run (since for example there are hard-coded paths in there) and now want to verify whether everything works as expected by using the [pre-trained weights you provide in the repo](https://drive.google.com/file/d/1RBHC1IDLVRNEiuO7qk3sWEf5HeHIyMRp/view?usp=sharing). Unfortunately, the tar archive is corrupt.

Could you upload the weights again maybe? And do I understand correctly that those are the weights after the 4th epoch?

Best,
Florian

**Comment by Mengmi** [comment]
Are you using pytorch in python 3, Anaconda environment?
What is the error if there is corruption?
I tried to download the tar model and re-loaded it using pytorch. Everything works fine on my machine.

**Comment by bomatter** [comment]
Make sure that you adhere to the same directory structure, since the checkpoint is serialized with Python's pickle module.
Did you save the checkpoint to `Put-In-Context/pytorch/recurrentVA_obj/models`?

**Comment by florianblume** [comment]
Thanks for the replies! The error was on my side, it is working now, thanks again. Closing this issue.
